grails-app/domain/br/edu/unirn/seguranca/Usuario.groovy
package br.edu.unirn.seguranca

import br.edu.unirn.comum.Pessoa;
import br.edu.unirn.tipos.TipoUsuario;

class Usuario {

	String nome
	String email
	String login
	String senha
	int countAcesso = 0
	Date ultimoAcesso
	boolean habilitado = true
	TipoUsuario tipoUsuario
	
	static constraints = {
		login blank: false, unique: true
		senha blank: false
		nome blank:false
		ultimoAcesso nullable:true 
		email email:true, blank:false
	}
		
	String toString(){
		nome
	}
	
	/*def beforeInsert() {
		encodePassword()
	}

	def beforeUpdate() {
		if (isDirty('senha')) {
			encodePassword()
		}
	}*/
}

grails-app/views/usuario/_form.gsp
<%@ page import="br.edu.unirn.seguranca.Usuario" %>
<%@ page import="br.edu.unirn.tipos.TipoUsuario" %>

<div class="form-group">
    <label class="col-md-2 control-label" for="nome">Nome</label>

    <div class="col-md-4">
   		<g:textField name="nome"  value="${usuarioInstance?.nome}" data-validate="{required: true, messages:{required:'Campo obrigatorio'}}" class="form-control input-sm" placeholder="Nome..."/>
    </div>
</div> 

<div class="form-group">
    <label class="col-md-2 control-label" for="login">Login</label>

    <div class="col-md-3">
    	<g:textField name="login"  value="${usuarioInstance?.login}" data-validate="{required: true, messages:{required:'Campo obrigatorio'}}" class="form-control input-sm" placeholder="Login..."/>
    </div>
</div>

<div class="form-group">
    <label class="col-md-2 control-label" for="email">E-mail</label>

    <div class="col-md-3">
    	<g:textField type="email" name="email"  value="${usuarioInstance?.email}" data-validate="{required: true,email:true messages:{required:'Campo obrigatorio',email:'Digite um E-mail valido'}}" class="form-control input-sm" placeholder="Email..."/>
    </div>
</div>  


<div class="form-group">
    <label class="col-md-2 control-label" for="senha">Senha</label>

    <div class="col-md-2">
    	<g:passwordField name="senha" data-validate="{required: true, messages:{required:'Campo obrigatorio'}}" class="form-control input-sm"/>
    </div>
    
    <label class="col-md-1 control-label" for="senhaConfirm">Conf.Senha</label>

    <div class="col-md-2">
    	<g:passwordField name="senhaConfirm" data-validate="{required: true,equalTo:'#senha' messages:{required:'Campo obrigatorio',equalTo:'Senhas diferentes'}}" class="form-control input-sm"/>
    </div>
</div>  

<div class="form-group">
	<label class="col-md-2 control-label" for="tipoUsuario">Tipo Usuario</label>

    <div class="col-md-2">
    	<g:select name="tipoUsuario" from="${TipoUsuario.values()}" keys="${TipoUsuario.values()*.name()}" optionValue="descricao" class="form-control input-sm"/>
    </div>
</div>

<div class="form-group">
	<div class="col-lg-offset-2 col-lg-10 col-md-offset-2 col-md-10">
		<div class="checkbox">
		    <label>
		      <g:checkBox name="habilitado" value="${usuarioInstance?.habilitado}" /> Habilitado
		    </label>
		</div>
	</div>
</div>

grails-app/views/usuario/_resultList.gsp
<%@ page import="br.edu.unirn.seguranca.Usuario"%>

	<p class="help-block" id="qntdRegistro">Quantidade - ${usuarioInstanceTotal}</p>
            
            <table class="table table-hover table-condensed table-bordered">
            <thead>
                <tr>
                    <th style="width:19px;">
						<span id="popoverAlert"></span>
                        <input type="checkbox" id="checkTodos" value="">
                    </th>
	                <g:if test="${actionName == 'buscaSimples'}">
	                    <g:sortableColumn params="${[nomeBuscaSimples: nomeBuscaSimples]}" property="login" title="${message(code: 'usuario.login.label', default: 'Login')}" />
						<g:sortableColumn params="${[nomeBuscaSimples: nomeBuscaSimples]}" property="nome" title="${message(code: 'usuario.nome.label', default: 'Nome')}" />
						<g:sortableColumn params="${[nomeBuscaSimples: nomeBuscaSimples]}" property="email" title="${message(code: 'usuario.email.label', default: 'E-Mail')}" />
						<g:sortableColumn params="${[nomeBuscaSimples: nomeBuscaSimples]}" property="habilitado" title="${message(code: 'usuario.habilitado.label', default: 'Habilitado')}" />
	                </g:if>
	                <g:else>
	                	<g:sortableColumn property="login" title="${message(code: 'usuario.login.label', default: 'Login')}" />
						<g:sortableColumn property="nome" title="${message(code: 'usuario.nome.label', default: 'Nome')}" />
						<g:sortableColumn property="email" title="${message(code: 'usuario.email.label', default: 'E-Mail')}" />
						<g:sortableColumn property="habilitado" title="${message(code: 'usuario.habilitado.label', default: 'Habilitado')}" />
	    	        </g:else>
                    
					<th style="width: 10%;">Editar</th>
                </tr>
            </thead>
            <tbody>
                <g:each in="${usuarioInstanceList}" var="usuarioInstance">
	                
	                <tr id="${usuarioInstance?.id}">
	                    <td>
	                        <input type="checkbox" class="checkSimples" data-registroId="${usuarioInstance?.id}" data-campo="${controllerName}ID" value="">
	                    </td>
	                    <td>${fieldValue(bean: usuarioInstance, field: "login")}</td>
						
						<td>${fieldValue(bean: usuarioInstance, field: "nome")}</td>
							
						<td>${fieldValue(bean: usuarioInstance, field: "email")}</td>
						
						<td><g:formatBoolean boolean="${usuarioInstance?.habilitado}" /></td>
	                    <td style="text-align: center;"><g:link class="btn btn-xs btn-default" action="edit" id="${usuarioInstance?.id}">Editar</g:link></td>
	                </tr>
	                
	           </g:each>
            </tbody>
        </table>
        <div class="row pagination-table">
	        <div class="pagination pagination-centered col-lg-12">
                <g:if test="${actionName == 'buscaSimples' }">
                    <g:paginate params="${[nomeBuscaSimples: nomeBuscaSimples]}" total="${usuarioInstanceTotal}" />
                </g:if>
                <g:else>
                	<g:paginate total="${usuarioInstanceTotal}" />
    	        </g:else>
			</div>
		</div>

grails-app/views/usuario/create.gsp
<%@ page import="br.edu.unirn.seguranca.Usuario" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'usuario.label', default: 'Usuario')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<div class="row">
<div class="col-lg-12 col-md-12">
    
    <ol class="breadcrumb">
      <li><a href="${createLink(uri: '/')}">Vis&atilde;o Geral</a></li>
      <li><g:link action="list">Usu&aacute;rios</g:link></li>
      <li class="active">Cadastrar</li>        
    </ol>

</div><!-- /.col-md-12 -->
</div>
<div class="row">
<div class="col-lg-12 col-md-12">
    
    <div class="panel panel-default">
	
        <div class="panel-heading">
           Novo Usu&aacute;rio
        </div><!-- /.panel-heading -->
        
        <div class="panel-body">
        <g:if test="${flash.message}">
			<div class="alert alert-dismissable alert-danger">
				  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
				  ${flash.message}	
			</div>
		</g:if>
        <g:form action="save" class="form-horizontal formValidate" role="form">
        	<fieldset class="groupFields"> 
						
				<g:render template="form" />
        		
        		<div class="btn-group">
        			   <g:link action="list" class="btn btn-default pull-right"><span class="icon-arrow-left"></span> Voltar</g:link>
                </div> 
                <div class="btn-group">
                        <button type="submit" class="btn btn-success pull-right">Salvar <span class="icon-ok"></span></button>
                </div>  
                
                
            </fieldset>
        </g:form>
            
        </div><!-- /.panel-body -->
        

    </div><!-- /.panel -->

</div><!-- /.col-md-12 -->
</div>
<g:javascript>
	configuracoesGerais.ativarMenu("configuracoesMenu");
</g:javascript>
	</body>
</html>

grails-app/views/usuario/edit.gsp
<%@ page import="br.edu.unirn.seguranca.Usuario" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'usuario.label', default: 'Usuario')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
<div class="col-lg-12 col-md-12">
    
    <ol class="breadcrumb">
      <li><a href="${createLink(uri: '/')}">Vis&atilde;o Geral</a></li>
      <li><g:link action="list">Usu&aacute;rios</g:link></li>
      <li class="active">Editar</li>        
    </ol>

</div><!-- /.col-md-12 -->

<div class="col-lg-12 col-md-12">
    
    <div class="panel panel-default">

        <div class="panel-heading">
           Editar Usu&aacute;rio
        </div><!-- /.panel-heading -->
        
        <div class="panel-body">
		<g:if test="${flash.message}">
			<div class="alert alert-dismissable alert-danger">
				  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
				  ${flash.message}	
			</div>
		</g:if>
		<g:form name="delete" action="delete">
			<g:hiddenField name="id" value="${usuarioInstance?.id}"/>
		</g:form>
        <g:form action="update" class="form-horizontal formValidate" role="form">
        	<fieldset class="groupFields"> 
        	
				<g:hiddenField name="id" value="${usuarioInstance?.id}"/>		
				
				<g:render template="form" />
        		
        		<div class="btn-group">
                       <g:link action="list" class="btn btn-default pull-right"><span class="icon-arrow-left"></span> Voltar</g:link>
                </div> 
                <div class="btn-group">
                		<button type="button" class="btn linkDelete" ><span class="icon-trash"></span> Desabilitar</button>
                </div> 
                <div class="btn-group">
                		<button class="btn btn-success pull-right" type="submit"><span class="icon-pencil"></span> Editar</button>
                </div>  
                
                
            </fieldset>
        </g:form>
            
        </div><!-- /.panel-body -->
        

    </div><!-- /.panel -->

</div><!-- /.col-md-12 -->
<g:javascript>
	configuracoesGerais.ativarMenu("configuracoesMenu");
</g:javascript>
	</body>
</html>

grails-app/views/usuario/list.gsp
<%@ page import="br.edu.unirn.seguranca.Usuario" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'usuario.label', default: 'Usuario')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
	<div class="col-lg-12 col-md-12">
                    
    <ol class="breadcrumb">
      <li><a href="${createLink(uri: '/')}">Vis&atilde;o Geral</a></li>
      <g:if test="${actionName == 'buscaSimples'}">
      	<li><g:link action="list">Cl&iacute;nicas</g:link></li> 
      	<li class="active">Resultado da Busca</li>  
      </g:if>
      <g:else>
      	<li class="active">Cl&iacute;nicas</li>
      </g:else>         
    </ol>

</div><!-- /.col-md-12 -->

<div class="col-lg-12 col-md-12">
    
    <div class="panel panel-default">

        <div class="panel-heading">
            Usu&aacute;rios
        </div><!-- /.panel-heading -->
        
        <div class="panel-body">
         	<g:if test="${flash.message}">
         		<div class="alert alert-dismissable alert-success">
					  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
					   <a href="${createLink(action: 'edit',params:[id:flash.id] )}" class="alert-link"><strong>${flash.nome} - </strong></a>
					   ${flash.message}	
				</div>
         	</g:if>
         	
            <fieldset>
            	<div class="row">
	            	<div class="col-md-6">
	            	<g:if test="${actionName == 'buscaSimples'}">
	            		<div class="btn-group">
		                      <g:link action="list" type="button" class="btn btn-default"><span class="icon-arrow-left"></span> Voltar</g:link>
		                </div>
	            	</g:if>
		                <div class="btn-group">
		                		<g:link action="create" class="btn btn-success"><span class="icon-hospital"></span> Novo Usu&aacute;rio</g:link>
		                </div>
		                <div class="btn-group">
                        	<button type="button" class="btn" id="deleteChecked" data-controller="${controllerName}"><span class="icon-trash"></span> Desabilitar</button>
                		</div>  
	               	</div>
	                <div class="col-md-3 pull-right">
	
	                    <g:form action="buscaSimples" role="search">

                            <div class="input-group">
                                <input name="nomeBuscaSimples" type="text" class="form-control" placeholder="Pesquisar...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="submit"><span class="icon-search"></span></button>
                                </span>
                            </div>

                    	</g:form>
						
	                </div><!-- /.col-md-6 -->
            	</div>
            </fieldset>
            
            	<g:render template="resultList"/>
            
        </div><!-- /.panel-body -->
        

    </div><!-- /.panel -->

</div><!-- /.col-md-12 -->	
<g:javascript>
	configuracoesGerais.ativarMenu("configuracoesMenu");
</g:javascript>
	</body>
</html>

grails-app/views/usuario/show.gsp
<%@ page import="br.edu.unirn.seguranca.Usuario" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'usuario.label', default: 'Usuario')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<div id="show-usuario" class="contentCrud" role="main">
			<div class="box corner-all">
				<div class="box-header grd-white color-black corner-top">
					<span>Usu&aacute;rio</span>
				</div>
				<div class="box-body">
					<g:if test="${flash.message}">
						<div class="alert" role="status">
							 <button type="button" class="close" data-dismiss="alert">&times;</button>
							 <strong>${flash.message}</strong>
						</div>
					</g:if>
					<ol class="property-list usuario">
					
						<g:if test="${usuarioInstance?.nome}">
						<li class="fieldcontain">
							<span id="nome-label" class="property-label"><g:message code="usuario.nome.label" default="Nome" /></span>
							
								<span class="property-value" aria-labelledby="nome-label"><g:fieldValue bean="${usuarioInstance}" field="nome"/></span>
							
						</li>
						</g:if>
						
						<g:if test="${usuarioInstance?.email}">
						<li class="fieldcontain">
							<span id="email-label" class="property-label"><g:message code="usuario.email.label" default="E-mail" /></span>
							
								<span class="property-value" aria-labelledby="email-label"><g:fieldValue bean="${usuarioInstance}" field="email"/></span>
							
						</li>
						</g:if>
					
						<g:if test="${usuarioInstance?.login}">
						<li class="fieldcontain">
							<span id="username-label" class="property-label"><g:message code="usuario.username.label" default="Login" /></span>
							
								<span class="property-value" aria-labelledby="username-label"><g:fieldValue bean="${usuarioInstance}" field="login"/></span>
							
						</li>
						</g:if>
					
					
						<g:if test="${usuarioInstance?.habilitado}">
						<li class="fieldcontain">
							<span id="enabled-label" class="property-label"><g:message code="usuario.enabled.label" default="Habilitado" /></span>
							
								<span class="property-value" aria-labelledby="enabled-label"><g:formatBoolean boolean="${usuarioInstance?.habilitado}" /></span>
							
						</li>
						</g:if>
						
						<g:if test="${usuarioInstance?.ultimoAcesso}">
						<li class="fieldcontain">
							<span id="enabled-label" class="property-label"><g:message code="usuario.enabled.label" default="Ultimo Acesso" /></span>
							
								<span class="property-value" aria-labelledby="enabled-label"><g:formatDate format="dd/MM/yyyy" date="${usuarioInstance?.ultimoAcesso}" true="Sim" false="Não"/></span>
							
						</li>
						</g:if>
								
						
					</ol>
					<g:form class="form">
						<div class="form-actions">
							<g:hiddenField name="id" value="${usuarioInstance?.id}" />
							<g:link class="btn btn-primary" action="edit" id="${usuarioInstance?.id}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
						</div>
					</g:form>
				</div>
			</div>
		</div>
	</body>
</html>

grails-app/views/usuario/solicitar.gsp
<%@ page import="br.edu.unirn.seguranca.Usuario"%>
<!doctype html>
<html lang="en">
<head>
<title>Clínicas Integradas - Núcleo DEV UNIRN</title>
<r:require module="bootstrap" />
<r:layoutResources />

<style type="text/css">
/* Override some defaults */
html,body {
	background-color: #eee;
}

body {
	padding-top: 100px;
}

.container {
	width: 300px;
}

/* The white background content wrapper */
.container>.content {
	background-color: #fff;
	padding: 20px;
	margin: 0 -20px;
	-webkit-border-radius: 10px 10px 10px 10px;
	-moz-border-radius: 10px 10px 10px 10px;
	border-radius: 10px 10px 10px 10px;
	-webkit-box-shadow: 0 1px 2px rgba(0, 0, 0, .15);
	-moz-box-shadow: 0 1px 2px rgba(0, 0, 0, .15);
	box-shadow: 0 1px 2px rgba(0, 0, 0, .15);
}

.login-form {
	margin-left: 35px;
}

legend {
	margin-right: -50px;
	font-weight: bold;
	color: #404040;
}
</style>
</head>

<body>
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container-fluid">
				<a href="${createLink(uri: '/')}" class="brand">Sistema das
					Clínicas Integradas - UNIRN</a>
			</div>
		</div>
	</div>
	<div class="container">
		<div class="content">
			<div class="row">
				<div class="login-form">
					<g:hasErrors bean="${usuarioInstance}">
						<ul class="errors" role="alert">
							<g:eachError bean="${usuarioInstance}" var="error">
								<li
									<g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
										error="${error}" /></li>
							</g:eachError>
						</ul>
					</g:hasErrors>
					<g:if test="${flash.message}">
						<div class="alert alert-success">
							${flash.message}
						</div>
					</g:if>
					<h2>Solicitação de Cadastro</h2>
					<g:form action="efetivarSolicitacao" autocomplete='off'>
						<fieldset>
							<div
								class="clearfix ${hasErrors(bean: usuarioInstance, field: 'nome', 'error')} required">
								<g:textField name="nome" required=""
									value="${usuarioInstance?.nome}" placeholder="Nome" />
							</div>

							<div
								class="clearfix ${hasErrors(bean: usuarioInstance, field: 'email', 'error')} required">
								<g:textField name="email" required=""
									value="${usuarioInstance?.email}" placeholder="E-mail" />
							</div>

							<div
								class="clearfix ${hasErrors(bean: usuarioInstance, field: 'username', 'error')} required">

								<g:textField name="username" required=""
									value="${usuarioInstance?.username}" placeholder="Login" />
							</div>

							<div
								class="clearfix ${hasErrors(bean: usuarioInstance, field: 'password', 'error')} required">

								<g:passwordField name="password" required="" placeholder="Senha" />
							</div>

						</fieldset>
						<div class="form-actions">
							<g:submitButton name="create" class="btn btn-primary"
								value="Solicitar Cadastro" />
							<g:link controller="login" class="btn">Voltar</g:link>
						</div>
					</g:form>
				</div>
			</div>
		</div>
	</div>
</body>
</html>