grails-app/domain/br/edu/unirn/comum/Clinica.groovy
package br.edu.unirn.comum


class Clinica {
	
	String descricao
	Float valor
	boolean ativo = false
	
    static constraints = {
		descricao(nullable:false,unique:true)
		valor(nullable:false,blank:false)
    }
	
	static mapping = {
		sort('descricao')
	}
	
	String toString(){
		descricao
	}
	
}

grails-app/domain/br/edu/unirn/consulta/Agenda.groovy
package br.edu.unirn.consulta

import br.edu.unirn.comum.Clinica
import br.edu.unirn.tipos.Turno

class Agenda {

	Clinica clinica
	Float duracao
	String horaInicio
	String horaFim
	Turno turno
	boolean ativo = true
	
    static constraints = {
		horaInicio(blank:false,matches:"([01]?[0-9]|2[0-3]):[0-5][0-9]")
		horaFim(blank:false,matches:"([01]?[0-9]|2[0-3]):[0-5][0-9]")
    }
	
	static mapping = {
	}
}

grails-app/domain/br/edu/unirn/consulta/AlteracaoStatusConsulta.groovy
package br.edu.unirn.consulta

import java.util.Date;

import br.edu.unirn.seguranca.Usuario;

class AlteracaoStatusConsulta {

	Consulta consulta
	StatusConsulta statusConsultaAnterior
	StatusConsulta statusConsultaAtual
	String motivo
	
	Usuario usuarioMarcacao
	
	Date dateCreated
	
    static constraints = {
    }
}

grails-app/domain/br/edu/unirn/consulta/Consulta.groovy
package br.edu.unirn.consulta

import java.util.Date;

import br.edu.unirn.comum.Paciente
import br.edu.unirn.comum.Sala
import br.edu.unirn.seguranca.Usuario;
import br.edu.unirn.tipos.Turno;
import br.edu.unirn.utils.CalendarUtils;


class Consulta {

	Paciente paciente
	Date dataConsulta
	String horarioConsulta
	Sala sala
	Sala salaIndicacao
	String motivo
	String justificativa
	Float duracao
	StatusConsulta statusConsulta
	Turno turno
	
	Float valor
	StatusPagamento statusPagamento
	
	Usuario usuarioMarcacao
	
	Date dateCreated
	Date lastUpdated
	
    static constraints = {
		statusConsulta(nullable:true)
		statusPagamento(nullable:true)
		salaIndicacao(nullable:true)
    }
	
}

grails-app/domain/br/edu/unirn/consulta/FilaEspera.groovy
package br.edu.unirn.consulta

import br.edu.unirn.comum.Clinica;
import br.edu.unirn.comum.Pessoa
import br.edu.unirn.seguranca.Usuario;
import br.edu.unirn.tipos.StatusFilaEspera;
import br.edu.unirn.tipos.Turno;

class FilaEspera {
	
	String nome
	String motivo
	String telefoneContato
	Integer idade
	Turno turno
	StatusFilaEspera statusFilaEspera
	
	Pessoa pessoa
	Clinica clinica
	
	Usuario usuarioMarcacao
	
	Date dateCreated

    static constraints = {
		pessoa(nullable:true)
		motivo(blank:true)
		nome(blank:true,nullable:true)
		telefoneContato(blank:false)
    }
	
	static mapping = {
		sort "dateCreated", order: "desc"
	}
}

grails-app/domain/br/edu/unirn/consulta/StatusPagamento.groovy
package br.edu.unirn.consulta

import br.edu.unirn.tipos.TipoStatusConsulta;

class StatusPagamento {

   String nome
   String corListagem
	
    static constraints = {
		nome(blank:false)
    }
	
	static mapping = {
		cache true
	}
	
	String toString(){
		nome	
	}
}

grails-app/controllers/br/edu/unirn/consulta/AgendaController.groovy
package br.edu.unirn.consulta

import org.springframework.dao.DataIntegrityViolationException

class AgendaController {

    static allowedMethods = [save: "POST", update: "POST", delete: "POST"]

    def index() {
        redirect(action: "list", params: params)
    }

    def list(Integer max) {
        params.max = Math.min(max ?: 10, 100)
		def result = Agenda.createCriteria().list(params){
			eq("ativo", true)
		}
		
        [agendaInstanceList: result, agendaInstanceTotal: result.totalCount]
    }
	
	def buscaSimples(Integer max) {
		params.max = Math.min(max ?: 10, 100)
		params.offset = (params.offset ? params.offset.toInteger() : 0)
			
		def agendaCriteria = Agenda.createCriteria()
		def result = agendaCriteria.list(params){
			createAlias('clinica','c')
			eq("ativo", true)
			ilike('c.descricao',"${params.nomeBuscaSimples}%")
		}
		render(view:"list",model:[agendaInstanceList: result, agendaInstanceTotal:result.totalCount,nomeBuscaSimples:params.nomeBuscaSimples])
	}

    def create() {
        [agendaInstance: new Agenda(params)]
    }

    def save() {
        def agendaInstance = new Agenda(params)
		def query = {
			and{
				eq("clinica",agendaInstance.clinica)
				eq("turno",agendaInstance.turno)	
			}
		}
		def agendaExiste = Agenda.createCriteria().get(query)
		if(agendaExiste){
			flash.message = "Existe agenda cadastrada em ${agendaInstance.clinica.descricao} no turno ${agendaInstance.turno}"
			render(view: "create", model: [agendaInstance: agendaInstance])
			return
		}
		
        if (!agendaInstance.save(flush: true)) {
            render(view: "create", model: [agendaInstance: agendaInstance])
            return
        }

        flash.message = message(code: 'default.created.message', args: [message(code: 'agenda.label', default: 'Agenda'), agendaInstance.id])
        redirect(action: "show", id: agendaInstance.id)
    }

    def show(Long id) {
        def agendaInstance = Agenda.get(id)
        if (!agendaInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'agenda.label', default: 'Agenda'), id])
            redirect(action: "list")
            return
        }

        [agendaInstance: agendaInstance]
    }

    def edit(Long id) {
        def agendaInstance = Agenda.get(id)
        if (!agendaInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'agenda.label', default: 'Agenda'), id])
            redirect(action: "list")
            return
        }

        [agendaInstance: agendaInstance]
    }

    def update(Long id, Long version) {
		println params
        def agendaInstance = Agenda.get(id)
        if (!agendaInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'agenda.label', default: 'Agenda'), id])
            redirect(action: "list")
            return
        }

        if (version != null) {
            if (agendaInstance.version > version) {
                agendaInstance.errors.rejectValue("version", "default.optimistic.locking.failure",
                          [message(code: 'agenda.label', default: 'Agenda')] as Object[],
                          "Another user has updated this Agenda while you were editing")
                render(view: "edit", model: [agendaInstance: agendaInstance])
                return
            }
        }

        agendaInstance.properties = params
		
		def query = {
			and{
				eq("clinica",agendaInstance.clinica)
				eq("turno",agendaInstance.turno)
				ne('id',id)
			}
		}
		def agendaExiste = Agenda.createCriteria().get(query)
		if(agendaExiste){
			println "aqui"
			flash.message = "Existe agenda cadastrada em ${agendaInstance.clinica.descricao} no turno ${agendaInstance.turno}"
			render(view: "edit", model: [agendaInstance: agendaInstance])
			return
		}

        if (!agendaInstance.save(flush: true)) {
            render(view: "edit", model: [agendaInstance: agendaInstance])
            return
        }

        flash.message = message(code: 'default.updated.message', args: [message(code: 'agenda.label', default: 'Agenda'), agendaInstance.id])
        redirect(action: "show", id: agendaInstance.id)
    }

    def delete(Long id) {
        def agendaInstance = Agenda.get(id)
        if (!agendaInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'agenda.label', default: 'Agenda'), id])
            redirect(action: "list")
            return
        }

        try {
            agendaInstance.delete(flush: true)
            flash.message = message(code: 'default.deleted.message', args: [message(code: 'agenda.label', default: 'Agenda'), id])
            redirect(action: "list")
        }
        catch (DataIntegrityViolationException e) {
            flash.message = message(code: 'default.not.deleted.message', args: [message(code: 'agenda.label', default: 'Agenda'), id])
            redirect(action: "show", id: id)
        }
    }
}

grails-app/controllers/br/edu/unirn/consulta/AlteracaoStatusConsultaController.groovy
package br.edu.unirn.consulta

import grails.converters.JSON
import br.edu.unirn.comum.Paciente

class AlteracaoStatusConsultaController {

	def save() {
		def alteracaoStatusConsulta = new AlteracaoStatusConsulta(params)
		alteracaoStatusConsulta.usuarioMarcacao = session.usuario
		def consulta = Consulta.get(alteracaoStatusConsulta.consulta.id)
		
		if (alteracaoStatusConsulta.save(flush: true)) {
			consulta.statusConsulta = alteracaoStatusConsulta.statusConsultaAtual
			consulta.save(flush: true)
		}
		render ([status:consulta.statusConsulta.descricao,cor:consulta.statusConsulta?.corListagem,consulta:consulta.id] as JSON)
	}
	
	def historicoAlteracaoConsulta(){
		def paciente = Paciente.get(params.id)
		def query = {
			createAlias("consulta","consulta")
			createAlias("consulta.paciente","paciente")
			eq("paciente.id",paciente.id)	
		}
		
		//def listaAlteracaoConsulta = AlteracaoStatusConsulta.createCriteria().list(query)
		def listaAlteracaoConsulta = AlteracaoStatusConsulta.createCriteria().list(query)
		
		[listaAlteracaoConsulta:listaAlteracaoConsulta,pacienteInstance:paciente,listaConsulta:Consulta.findAllByPaciente(paciente)]	
	}
}

grails-app/controllers/br/edu/unirn/consulta/AlteracaoStatusPagamentoController.groovy
package br.edu.unirn.consulta

import grails.converters.JSON

class AlteracaoStatusPagamentoController {

	def update(){
		def idconsulta = Long.parseLong(params.consulta.id)
		def idstatusPagamento = Long.parseLong(params.statusPagamento.id)
		
		def consulta = Consulta.get(idconsulta)
		def paciente = consulta.paciente
		
		if(!paciente.pessoa.nome || !paciente.pessoa.dataNascimento || 
			!paciente.pessoa.ocupacao || !paciente.pessoa.logradouro || !paciente.pessoa.telefoneContato
			|| !paciente.pessoa.grauInstrucao){
			render([statusPaciente: false,pacienteId: paciente.id] as JSON)
			return
		}
		def statusConsulta = StatusPagamento.get(idstatusPagamento)
		def valor = Float.parseFloat(params.valor)
		
		if(consulta.save(flush:true)){
			consulta.statusPagamento = statusConsulta
			consulta.valor = valor
		}
		render([statusPaciente:true, status: consulta.statusPagamento.nome, cor: consulta.statusPagamento.corListagem, consulta: consulta.id] as JSON)
	}	
}

grails-app/controllers/br/edu/unirn/consulta/BuscaProfissionalController.groovy
package br.edu.unirn.consulta

class BuscaProfissionalController {

    def profissionalService
	
	def index() {
		render(view: "consulta", params: params)
	}
	
	def consulta(){
		if(String.valueOf(params.id) || params.nome){
			def resultado = profissionalService.buscaProfissional(params)
			
			if(resultado.isEmpty()){
				flash.message = "Sem resultados encontrados!"
			}
			[nome:params.nome,idenficador:params.id,profissionalLista:resultado]
		}else{
			flash.message =  "Selecione ao menos 1 filtro!"
		}
	}
}

grails-app/controllers/br/edu/unirn/consulta/FilaEsperaController.groovy
package br.edu.unirn.consulta

import org.springframework.dao.DataIntegrityViolationException

import br.edu.unirn.comum.Paciente;
import br.edu.unirn.comum.Sala;
import br.edu.unirn.tipos.StatusFilaEspera
import br.edu.unirn.tipos.Turno;

class FilaEsperaController {

    static allowedMethods = [save: "POST", update: "POST", delete: "POST"]

    def index() {
        redirect(action: "list", params: params)
    }

    def list(Integer max) {
        params.max = Math.min(max ?: 10, 100)
		
		def filaEsperaCriteria = FilaEspera.createCriteria()
		def result = filaEsperaCriteria.list(params){
			ne("statusFilaEspera",StatusFilaEspera.DESISTIU)
		}
        [filaEsperaInstanceList: result, filaEsperaInstanceTotal: result.totalCount]
    }
	
	def buscaSimples(Integer max) {
		params.max = Math.min(max ?: 10, 100)
		params.offset = (params.offset ? params.offset.toInteger() : 0)
			
		def filaEsperaCriteria = FilaEspera.createCriteria()
		def result = filaEsperaCriteria.list(params){
			ilike("nome","${params.nomeBuscaSimples}%")
		}
		render(view:"list",model:[filaEsperaInstanceList: result,filaEsperaInstanceTotal:result.totalCount,nomeBuscaSimples:params.nomeBuscaSimples])
	}
	
	def buscaAvancada(Integer max){
		params.max = Math.min(max ?: 10, 100)
		params.offset = (params.offset ? params.offset.toInteger() : 0)

		def filaEsperaCriteria = FilaEspera.createCriteria()
		def result = filaEsperaCriteria.list(params){
			if(params.nomeBuscaAvancada){
				ilike("nome","${params.nomeBuscaAvancada}%")
			}
			if(params.clinicaBuscaAvancada){
				eq("clinica.id",params.clinicaBuscaAvancada.toLong())
			}
			if(params.turnoBuscaAvancada){
				eq("turno",Turno[params.turnoBuscaAvancada])
			}
			if(params.statusBuscaAvancada){
				eq("statusFilaEspera", StatusFilaEspera[params.statusBuscaAvancada])
			}
			
		}
		render(view:"list",model:[filaEsperaInstanceList: result,filaEsperaInstanceTotal:result.totalCount,nomeBuscaAvancada:params.nomeBuscaAvancada,clinicaBuscaAvancada:params.clinicaBuscaAvancada,turnoBuscaAvancada:params.turnoBuscaAvancada,statusBuscaAvancada:params.statusBuscaAvancada])
	}

    def create() {
        [filaEsperaInstance: new FilaEspera(params)]
    }

    def save() {
        def filaEsperaInstance = new FilaEspera(params)
		filaEsperaInstance.statusFilaEspera = StatusFilaEspera.AGUARDANDO
		filaEsperaInstance.usuarioMarcacao = session.usuario
		if (filaEsperaInstance.pessoa.id == 0 ){
			filaEsperaInstance.pessoa = null
			filaEsperaInstance.nome = params.pessoaAutoComplete
		}
        if (!filaEsperaInstance.save(flush: true)) {
            render(view: "create", model: [filaEsperaInstance: filaEsperaInstance])
            return
        }

        flash.message = message(code: 'default.created.message', args: [message(code: 'filaEspera.label', default: 'FilaEspera'), filaEsperaInstance.id])
        redirect(action: "show", id: filaEsperaInstance.id)
    }

    def show(Long id) {
        def filaEsperaInstance = FilaEspera.get(id)
        if (!filaEsperaInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'filaEspera.label', default: 'FilaEspera'), id])
            redirect(action: "list")
            return
        }

        [filaEsperaInstance: filaEsperaInstance]
    }

    def edit(Long id) {
        def filaEsperaInstance = FilaEspera.get(id)
        if (!filaEsperaInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'filaEspera.label', default: 'FilaEspera'), id])
            redirect(action: "list")
            return
        }

        [filaEsperaInstance: filaEsperaInstance]
    }

    def update(Long id, Long version) {
        def filaEsperaInstance = FilaEspera.get(id)
        if (!filaEsperaInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'filaEspera.label', default: 'FilaEspera'), id])
            redirect(action: "list")
            return
        }

        if (version != null) {
            if (filaEsperaInstance.version > version) {
                filaEsperaInstance.errors.rejectValue("version", "default.optimistic.locking.failure",
                          [message(code: 'filaEspera.label', default: 'FilaEspera')] as Object[],
                          "Another user has updated this FilaEspera while you were editing")
                render(view: "edit", model: [filaEsperaInstance: filaEsperaInstance])
                return
            }
        }

        filaEsperaInstance.properties = params
		
		if(filaEsperaInstance?.pessoa?.id == 0){
			filaEsperaInstance.pessoa = null
		}

        if (!filaEsperaInstance.save(flush: true)) {
            render(view: "edit", model: [filaEsperaInstance: filaEsperaInstance])
            return
        }

        flash.message = message(code: 'default.updated.message', args: [message(code: 'filaEspera.label', default: 'FilaEspera'), filaEsperaInstance.id])
        redirect(action: "show", id: filaEsperaInstance.id)
    }

    def delete(Long id) {
        def filaEsperaInstance = FilaEspera.get(id)
        if (!filaEsperaInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'filaEspera.label', default: 'FilaEspera'), id])
            redirect(action: "list")
            return
        }

        filaEsperaInstance.statusFilaEspera = StatusFilaEspera.DESISTIU 
		filaEsperaInstance.save(flush:true)
		
        flash.message = "Status da Lista de Espera modificado para Desistiu."
        redirect(action: "list")
      
    }
	
	def deleteList(Long id) {
		params.list("filaEsperaID").each{
			def filaEsperaInstance = FilaEspera.get(it.toLong())
			if (!filaEsperaInstance) {
				render(status:500,text:"Registro n&atilde;o encontrado!")
				return
			}
			try {
				filaEsperaInstance.statusFilaEspera = StatusFilaEspera.DESISTIU
				filaEsperaInstance.save(flush: true)
				
				render(status:200,text:"Alterado com Sucesso!")
				return
			}
			catch (DataIntegrityViolationException e) {
				render(status:200,text:message(code: 'default.not.deleted.message', args: [message(code: 'filaEspera.label', default: 'Fila Espera'), id]))
				return
			}
		}

	}
	
	def marcar(Long id){
		def filaEsperaInstance = FilaEspera.get(id)
		
		def pacienteInstance
		
		filaEsperaInstance.statusFilaEspera = StatusFilaEspera.MARCOU
		filaEsperaInstance.save(flush:true)
		
		if (filaEsperaInstance.pessoa){
			pacienteInstance = Paciente.findByPessoa(filaEsperaInstance.pessoa)
		}
	
		if(pacienteInstance){
			//Caso paciente exista, marcar consulta
			redirect(controller:"consulta", action:"marcarConsultaFilaEspera", id:id)
		}else{
			//Caso contrario criar paciente
			redirect(controller:"paciente", action:"marcarConsultaFilaEspera", id:id)
		}
	}
}

grails-app/views/consulta/_resultList.gsp
<%@ page import="br.edu.unirn.comum.Paciente"%>

	<p class="help-block" id="qntdRegistro">Quantidade - ${consultaInstanceTotal}</p>
            
            <table class="table table-hover table-condensed table-bordered">
            <thead>
                <tr>
                    <g:if test="${actionName == 'buscaAvancada'}">
	                    <g:sortableColumn params="${[nomePacienteBuscaAvancada:nomePacienteBuscaAvancada,dataInicialBuscaAvancada: dataInicialBuscaAvancada,dataFimBuscaAvancada:dataFimBuscaAvancada,clinicaIdBuscaAvancada:clinicaIdBuscaAvancada,statusConsultaIdBuscaAvancada:statusConsultaIdBuscaAvancada]}" 
	                    property="id" title="Núm. Pront." />
    	                <g:sortableColumn params="${[nomePacienteBuscaAvancada:nomePacienteBuscaAvancada,dataInicialBuscaAvancada: dataInicialBuscaAvancada,dataFimBuscaAvancada:dataFimBuscaAvancada,clinicaIdBuscaAvancada:clinicaIdBuscaAvancada,statusConsultaIdBuscaAvancada:statusConsultaIdBuscaAvancada]}" 
    	                property="paciente.pessoa.nome" title="Nome Paciente" />
    	                <g:sortableColumn params="${[nomePacienteBuscaAvancada:nomePacienteBuscaAvancada,dataInicialBuscaAvancada: dataInicialBuscaAvancada,dataFimBuscaAvancada:dataFimBuscaAvancada,clinicaIdBuscaAvancada:clinicaIdBuscaAvancada,statusConsultaIdBuscaAvancada:statusConsultaIdBuscaAvancada]}" 
    	                property="dataConsulta" title="Data" />
                    </g:if>
	                <g:elseif test="${actionName == 'buscaSimples'}">
	                    <g:sortableColumn params="${[dataInicialBuscaSimples: dataInicialBuscaSimples,dataFimBuscaSimples:dataFimBuscaSimples]}" property="id" title="Núm. Pront." />
	    	            <g:sortableColumn params="${[dataInicialBuscaSimples: dataInicialBuscaSimples,dataFimBuscaSimples:dataFimBuscaSimples]}" property="paciente.pessoa.nome" title="Nome Paciente" />
	                	<g:sortableColumn params="${[dataInicialBuscaSimples: dataInicialBuscaSimples,dataFimBuscaSimples:dataFimBuscaSimples]}" property="dataConsulta" title="data" />
	                	
	                </g:elseif>
	                <g:else>
	                	<g:sortableColumn  property="paciente.numeroProntuario" title="Núm. Pront." />
	    	            <g:sortableColumn  property="paciente.pessoa.nome" title="Nome Paciente" />
	    	            <g:sortableColumn  property="dataConsulta" title="Data" />
	    	        </g:else>
                    <th>Tel.Contato</th>
				    <th>Sala</th>
				    <th>Hor&aacute;rio</th>
				    <th>Status Pg.</th>
				    <th>Reag.</th>
				    <th>Hist.</th>
				    <th>Status</th>
				</tr>
			</thead>
			<tbody>
				<g:each var="consultaInstance" in="${consultaInstanceList}">
					<tr id="Consulta${consultaInstance.id}">
						<td>${consultaInstance.paciente.numeroProntuario}</td>
						<td>${consultaInstance.paciente.pessoa.nome}</td>
						<td><g:formatDate date="${consultaInstance.dataConsulta}" format="dd/MM/yyyy"/> </td>
						<td>${consultaInstance.paciente.pessoa.telefoneContato}<g:if test="${consultaInstance.paciente.pessoa.telefoneCelular}">/${consultaInstance.paciente.pessoa.telefoneCelular}</g:if> </td>
						<td>${consultaInstance.sala.nome} (${consultaInstance.sala.clinica.descricao})</td>
						<td>${consultaInstance.horarioConsulta}</td>
						<td id="consulta-${consultaInstance.id}" style="background-color: ${consultaInstance?.statusPagamento?.corListagem}" class='td-status'><a href="#" onclick="alterarPagamentoConsulta(${consultaInstance.id})">${consultaInstance.statusPagamento}</a></td>
						<td><g:link action="reagendamento" id="${consultaInstance.id}"><g:img file="skin/next.png" onclick="return confirm('Deseja realmente reagendar a consulta!?');"/></g:link></td>
						<td><g:link action="historicoAlteracaoConsulta" id="${consultaInstance.paciente.id}" controller="alteracaoStatusConsulta"><g:img file="skin/database_edit.png"/></g:link></td>
						<td style="background-color: ${consultaInstance?.statusConsulta?.corListagem}" class='td-status'><a href="#" onclick="alterarStatusConsulta(${consultaInstance.statusConsulta.id},${consultaInstance.id})">${consultaInstance.statusConsulta}</a></td>
					</tr>
				</g:each>
            </tbody>
        </table>
        <div class="row pagination-table">
	        <div class="pagination pagination-centered col-lg-12">
	        	<g:if test="${actionName == 'buscaAvancada' }">
	                   <g:paginate params="${[nomePacienteBuscaAvancada:nomePacienteBuscaAvancada,dataInicialBuscaAvancada: dataInicialBuscaAvancada,dataFimBuscaAvancada:dataFimBuscaAvancada,clinicaIdBuscaAvancada:clinicaIdBuscaAvancada,statusConsultaIdBuscaAvancada:statusConsultaIdBuscaAvancada]}" 
	                   total="${consultaInstanceTotal}" />
                    </g:if>
	                <g:elseif test="${actionName == 'buscaSimples' }">
	                    <g:paginate params="${[dataInicialBuscaSimples: dataInicialBuscaSimples,dataFimBuscaSimples:dataFimBuscaSimples]}" total="${consultaInstanceTotal}" />
	                </g:elseif>
	                <g:else>
	                	<g:paginate total="${consultaInstanceTotal}" />
	    	        </g:else>
			</div>
		</div>

grails-app/views/consulta/_terminarCadastroPaciente.gsp
<div id="terminarCadastroPaciente" title="Aten&ccedil;&atilde;o">
	<div class='col-md-12'>
		<div class="row">
			<div class="well">Algumas informa&ccedil;&otilde;es importantes do paciente 
			<span id='pacienteAlt'></span> est&atilde;o pendentes. &Eacute; necess&aacute;rio <strong>Concluir 
			o Cadastro</strong> para alterar o status do pagamento!</div>
			<g:form>
				<g:hiddenField name="id"/>
				<a id='btnConcluirCadastro' href='${g.createLink(controller:'paciente',action:'edit')}' class='btn btn-info btn-block'>Concluir Cadastro</a>
			</g:form>
		</div>
	</div>
</div>

grails-app/views/consulta/edit.gsp
<%@ page import="br.edu.unirn.consulta.Consulta" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'consulta.label', default: 'Consulta')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
		<resource:richTextEditor />
	</head>
	<body>
		<div id="edit-consulta" class="contentCrud" role="main">
			<g:hasErrors bean="${consultaInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${consultaInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<div class="box corner-all">
				<div class="box-header grd-white color-black corner-top">
						<span>Editar Consulta</span>
				</div>
				<div class="box-body">
					<g:if test="${flash.message}">
						<div class="alert" role="status">
							 <button type="button" class="close" data-dismiss="alert">&times;</button>
							 <strong>${flash.message}</strong>
						</div>
					</g:if>
				<g:form method="post" class="form-horizontal">
					<g:hiddenField name="id" value="${consultaInstance?.id}" />
					<g:hiddenField name="version" value="${consultaInstance?.version}" />
					<fieldset class="form">
						<g:render template="form"/>
					</fieldset>
					<div class="form-actions">
						<g:actionSubmit class="btn btn-primary" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
						<g:actionSubmit class="btn" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" formnovalidate="" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
					</div>
				</g:form>
			</div>
			<div id="modalCadastroPaciente">
				<g:form name="cadastarPacienteRapido" controller="paciente" action="cadastroRapido">
					<fieldset class="form">
						<div class="control-group">
							<label class="control-label" for="nome">
								Nome do Paciente
							</label>
							<div class="controls">
								<g:field type="text" name="nome" required="" class="input-xlarge"/>
							</div>
						</div>
						<div class="control-group">
							<label class="control-label" for="telefoneContato">
								Telefone de Contato
							</label>
							<div class="controls">
								<g:field type="text" name="telefoneContato" required=""/>
							</div>
						</div>
						<div class="control-group">
							<label class="control-label" for="telefoneContato">
								E-mail
							</label>
							<div class="controls">
								<g:field type="email" name="email"/>
							</div>
						</div>
					</fieldset>
					<div class="form-actions">
						<g:submitButton name="enviar" value="Cadastrar"/>
					</div>
				</g:form>
			</div>
		</div>
	</div>
<g:javascript>
	configuracoesGerais.ativarMenu("consultaMenu");
</g:javascript>
	</body>
</html>